# Generated by Django 5.2.6 on 2025-09-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_carts_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='product_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
