# Generated by Django 5.2.6 on 2025-09-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_orderproducts_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
