# Generated by Django 5.2.6 on 2025-09-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_carts_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
