# Generated by Django 5.2.6 on 2025-09-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_orderproducts_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
