# Generated by Django 5.2.6 on 2025-09-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_orderproducts_address_orderproducts_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
